drop schema if exists rps_schema cascade;

create schema if not exists rps_schema;

alter table if exists rps_schema.round
    drop constraint if exists game_id_foreign_key_constraint;

drop table if exists rps_schema.game cascade;

drop table if exists rps_schema.player_statistics cascade;

drop table if exists rps_schema.round cascade;

create table rps_schema.game
(
    id     int generated by default as identity,
    status varchar(255),
    primary key (id)
);

create table rps_schema.player_statistics
(
    player_id int generated by default as identity,
    draws     int,
    loses     int,
    rounds    int,
    wins      int,
    primary key (player_id)
);

create table rps_schema.round
(
    id            int generated by default as identity,
    computer_move varchar(255),
    player_move   varchar(255),
    result        varchar(255),
    game_id       int,
    primary key (id)
);


alter table if exists rps_schema.round
    add constraint game_id_foreign_key_constraint
        foreign key (game_id)
            references rps_schema.game